export const WORD_LENGTH = 5;

export const PHASE_CONFIGS = [
  { words: 1, maxAttempts: 6 },
  { words: 2, maxAttempts: 7 },
  { words: 3, maxAttempts: 8 },
  { words: 4, maxAttempts: 9 },
] as const;

export const TOTAL_PHASES = PHASE_CONFIGS.length;

export const WORD_BANK = [
  "amigo",
  "aviao",
  "banco",
  "barco",
  "beijo",
  "bolsa",
  "brisa",
  "cabra",
  "cacto",
  "canal",
  "canto",
  "carro",
  "carta",
  "chave",
  "chuva",
  "claro",
  "coral",
  "curva",
  "dente",
  "festa",
  "folha",
  "forca",
  "fruta",
  "fugir",
  "gosto",
  "grito",
  "hotel",
  "jogar",
  "julho",
  "lente",
  "livro",
  "lugar",
  "manga",
  "marco",
  "mudar",
  "nobre",
  "nuvem",
  "pedra",
  "piano",
  "pista",
  "praia",
  "prato",
  "reino",
  "risco",
  "rosto",
  "sabor",
  "salto",
  "sinal",
  "sonho",
  "tarde",
  "tempo",
  "terra",
  "tinta",
  "traje",
  "trigo",
  "vazio",
  "verde",
  "viola",
  "vital",
].map((word) => word.toUpperCase());

export const KEYBOARD_ROWS = [
  ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L", "BACKSPACE"],
  ["Z", "X", "C", "V", "B", "N", "M", "ENTER"],
] as const;
